apiVersion: apps/v1
kind: Deployment
metadata:
  name: project1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: project1
  template:
    metadata:
      labels:
        app: project1
    spec:
        containers:
        - name: project1
          image: mbdocker001/project1:latest
---
apiVersion: v1
kind: Service
metadata:
  name: project1
spec:
  selector:
    app: project1
  type: NodePort  
  ports:
  - name: http
    protocol: TCP
    port: 8085
    nodePort: 30020
 